### ISSUE TITLE
Build failing for newest version

### ISSUE THREAD

**Issue by JannikZed** [auchri/docker-nginx-piwik#3]
Hi there,
I was just trying to use your container to replace the one with the slow, old apache. I recognized, that your last automated build is failing on dockerhub: https://hub.docker.com/r/auchri/docker-nginx-piwik/builds/bvhjhtzvvroux3xhsygo9z4/

Would you mind taking a look into that?

Kind regards
Jannik

**Comment by auchri** [comment]
Hi,

sorry, I didn't notice the issue 😞 

I pulled in changes from a fork two weeks ago, the builds are now working again.
I've also added tags to target a specific piwik version.
